spring.application.name=url-shortener

spring.datasource.url = jdbc:mysql://localhost:3306/urlshortenerdb
spring.datasource.username = root
spring.datasource.password = rootroot
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

jwt.secret = 283d0111db9dcbe6e7e8919b8a0028dd
jwt.expiration = 172800000
